# Configurations
title:            VOTEIT Help Center
longtitle:        VOTEIT Help Center
author:           VOTEIT
email:            
description: >
  Help center for all kinds of usecases of VOTEIT.

version:          1.0
gitbook_version:  3.2.3

url:              'http://www.voteit.top'
baseurl:          '/help'
rss:              RSS
toc:
    enabled: true
# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  toc:                    toc
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
